before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: iCVSLDiFpTlIGMgu1EGO+5JTNUB0rJuOsd8m2ap5bz71pTUTi5RpzyBIOlTCOFTc6xMsrnPHlqbMPPybwQRRekxdWCVyinzr25nZRr38fEQCaGrxNBctAJI7yJ4hM7n1U31ggSHnFhNY9PQKp+PS5rECQ6GyNkv1EsJJ+XwKUhn7DO3mkjkiYhs39pXpb8VHz+kb0w8YjEhjov0tDVPuYUQpd7ADq3enO+dKBXz9t5a4pvEXqLN8ipgkhMTtQXeFzPiwfsnHLfePBtjHWHCUXJ9QGhwAdaBEGrwNtBscdOiHy9WqaO1pnOXYQmuacNqkdSRzV0ew6icoiOarNREA95/py6I70R9Jim4sA1rOBYp5wo0wq8R/n19vsoZqS1wgDSXo2yUes/NoG6mHue9vHuGvcGsqN/8ZHzzMlXFIEQqE09QD3ukqYyAwjIagNQCqJoDtHTUnP+pMuvXvbsbeoAuJWVskUmmyLMUdpNpNu+MNWGTxQ2Jx2vTkBPiFQOd0QS5N+XzoMCBUtiIE+nHHTEVc4O0JX1U7rD+z6qImyB7vQUeJP+mo75M7A9IyQ5r8X8uo2X5rZPPUozPnjTEZt+ROC4Gz8adD/bM1BDxtpoHxQlccubyvzyCtD+RZv5c+M36NWCQXtObKJ7Y8OTZGeVeYTGFTDrGE/X+lc6pMaQc= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
